# Generated by Django 5.2.3 on 2026-06-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customerorder_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Debit / Credit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Payment Apps'), ('online', 'Online Payment')], default='cod', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Debit / Credit Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Payment Apps'), ('online', 'Online Payment')], max_length=16),
        ),
    ]
