# Generated by Django 5.2.3 on 2026-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customerorder_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
